# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-26 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseComment',
            new_name='UserComments',
        ),
    ]
