# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-26 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20180726_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomments',
            old_name='comment',
            new_name='comments',
        ),
    ]
